# Generated by Django 5.0.6 on 2024-06-04 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="sponsor",
            new_name="sponsors",
        ),
    ]
