# Generated by Django 5.0.6 on 2024-06-04 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_rename_sponsor_activity_sponsors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Activity",
            new_name="CampusActivity",
        ),
        migrations.RenameModel(
            old_name="ActivityRequest",
            new_name="CampusActivityRequest",
        ),
    ]
