# Generated by Django 5.0.6 on 2024-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_rename_activity_campusactivity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusactivity",
            name="planning_document",
            field=models.FileField(
                blank=True, null=True, upload_to="docs/planning_documents/"
            ),
        ),
    ]
