# Generated by Django 5.0 on 2024-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0002_alter_department_head_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
