# Generated by Django 5.0 on 2024-05-21 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0003_alter_department_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="head_user",
        ),
    ]
