# Generated by Django 5.0 on 2024-05-21 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0004_remove_department_head_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdepartment",
            old_name="department_id",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="userdepartment",
            old_name="user_id",
            new_name="user",
        ),
    ]
