# Generated by Django 5.0 on 2024-05-22 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0005_rename_department_id_userdepartment_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdepartment",
            options={"ordering": ["joined"]},
        ),
        migrations.AddField(
            model_name="department",
            name="head_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
